services:
  postgres:
    image: postgres:15
    container_name: ecom-postgres
    environment:
      POSTGRES_DB: hasilaza_db
      POSTGRES_USER: hasilaza_user_admin
      POSTGRES_PASSWORD: H@siLaz@.2025
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - ecom-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hasilaza_user_admin -d hasilaza_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-api:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    container_name: ecom-backend-api
    ports:
      - "5001:8080"
    volumes:
      - product_images:/app/wwwroot/products
      - ./backend-api/src/EcomBackend.Api/appsettings.Production.json:/app/appsettings.Production.json:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - ecom-network

  admin-ecom:
    build:
      context: ./admin-ecom
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://api.yoobouko-hasilazamotor.com/api
        - NEXT_PUBLIC_STATIC_URL=https://api.yoobouko-hasilazamotor.com
    container_name: ecom-admin
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.yoobouko-hasilazamotor.com/api
    depends_on:
      - backend-api
    restart: always
    networks:
      - ecom-network

  e-com:
    build:
      context: ./e-com
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://api.yoobouko-hasilazamotor.com/api
        - NEXT_PUBLIC_STATIC_URL=https://api.yoobouko-hasilazamotor.com
    container_name: ecom-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.yoobouko-hasilazamotor.com/api
    depends_on:
      - backend-api
    restart: always
    networks:
      - ecom-network

networks:
  ecom-network:
    driver: bridge

volumes:
  postgres_data:
  product_images:
